USE [master]
GO

/****** Object:  Database [EventosDB]    Script Date: 7/1/2026 13:30:21 ******/
CREATE DATABASE [EventosDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EventosDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\EventosDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EventosDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\EventosDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EventosDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EventosDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EventosDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EventosDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EventosDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EventosDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EventosDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EventosDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EventosDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EventosDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EventosDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EventosDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EventosDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EventosDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EventosDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EventosDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EventosDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EventosDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EventosDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EventosDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EventosDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EventosDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EventosDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EventosDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EventosDB] SET  MULTI_USER 
GO

ALTER DATABASE [EventosDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EventosDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EventosDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EventosDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EventosDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EventosDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EventosDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [EventosDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [EventosDB] SET  READ_WRITE 
GO

USE [EventosDB]
GO

/****** Object:  Table [dbo].[Asistentes]    Script Date: 7/1/2026 13:30:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Asistentes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
	[Telefono] [int] NULL,
 CONSTRAINT [PK_Asistentes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [EventosDB]
GO

/****** Object:  Table [dbo].[Eventos]    Script Date: 7/1/2026 13:31:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Eventos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreEvento] [nvarchar](50) NULL,
	[FechaInicio] [date] NULL,
	[FechaFin] [date] NULL,
	[Lugar] [nvarchar](50) NULL,
 CONSTRAINT [PK_Eventos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [EventosDB]
GO

/****** Object:  Table [dbo].[EventosAsistentes]    Script Date: 7/1/2026 13:31:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EventosAsistentes](
	[IdEvento] [int] NOT NULL,
	[IdAsistente] [int] NOT NULL,
 CONSTRAINT [PK_EventosAsistentes] PRIMARY KEY CLUSTERED 
(
	[IdEvento] ASC,
	[IdAsistente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EventosAsistentes]  WITH CHECK ADD  CONSTRAINT [FK_EventosAsistentes_Asistentes] FOREIGN KEY([IdAsistente])
REFERENCES [dbo].[Asistentes] ([Id])
GO

ALTER TABLE [dbo].[EventosAsistentes] CHECK CONSTRAINT [FK_EventosAsistentes_Asistentes]
GO

ALTER TABLE [dbo].[EventosAsistentes]  WITH CHECK ADD  CONSTRAINT [FK_EventosAsistentes_Eventos] FOREIGN KEY([IdEvento])
REFERENCES [dbo].[Eventos] ([Id])
GO

ALTER TABLE [dbo].[EventosAsistentes] CHECK CONSTRAINT [FK_EventosAsistentes_Eventos]
GO

