USE [master]
GO

/****** Object:  Database [Mascotas_DB2]    Script Date: 28/12/2025 11:45:44 ******/
CREATE DATABASE [Mascotas_DB2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Mascotas_DB2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Mascotas_DB2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Mascotas_DB2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Mascotas_DB2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mascotas_DB2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Mascotas_DB2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET ARITHABORT OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Mascotas_DB2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Mascotas_DB2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Mascotas_DB2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Mascotas_DB2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Mascotas_DB2] SET  MULTI_USER 
GO

ALTER DATABASE [Mascotas_DB2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Mascotas_DB2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Mascotas_DB2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Mascotas_DB2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Mascotas_DB2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Mascotas_DB2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Mascotas_DB2] SET QUERY_STORE = ON
GO

ALTER DATABASE [Mascotas_DB2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Mascotas_DB2] SET  READ_WRITE 
GO


USE [Mascotas_DB2]
GO

/****** Object:  Table [dbo].[Usuarios]    Script Date: 28/12/2025 11:47:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NULL,
	[Apellido] [varchar](100) NULL,
	[Email] [varchar](100) NULL,
	[Clave] [varchar](50) NULL,
	[FechaRegistro] [datetime] NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



USE [Mascotas_DB2]
GO

/****** Object:  Table [dbo].[Mascotas]    Script Date: 28/12/2025 11:48:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Mascotas](
	[Id] [int] NOT NULL,
	[Nombre] [varchar](100) NULL,
	[Especie] [varchar](100) NULL,
	[Raza] [varchar](100) NULL,
	[FechaNacimiento] [date] NULL,
	[IdUsuario] [int] NULL,
 CONSTRAINT [PK_Mascotas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Mascotas]  WITH CHECK ADD  CONSTRAINT [FK_Mascotas_Usuarios] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuarios] ([Id])
GO

ALTER TABLE [dbo].[Mascotas] CHECK CONSTRAINT [FK_Mascotas_Usuarios]
GO



USE [Mascotas_DB2]
GO

/****** Object:  Table [dbo].[Citas.Veterinarias]    Script Date: 28/12/2025 11:48:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Citas.Veterinarias](
	[Id] [int] NOT NULL,
	[FechaCita] [datetime] NULL,
	[Razon] [varbinary](255) NULL,
	[IdMascota] [int] NULL,
 CONSTRAINT [PK_Citas.Veterinarias] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Citas.Veterinarias]  WITH CHECK ADD  CONSTRAINT [FK_Citas.Veterinarias_Mascotas] FOREIGN KEY([IdMascota])
REFERENCES [dbo].[Mascotas] ([Id])
GO

ALTER TABLE [dbo].[Citas.Veterinarias] CHECK CONSTRAINT [FK_Citas.Veterinarias_Mascotas]
GO



USE [Mascotas_DB2]
GO

/****** Object:  Table [dbo].[Registros.Salud]    Script Date: 28/12/2025 11:49:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Registros.Salud](
	[Id] [int] NOT NULL,
	[FechaRegistro] [date] NULL,
	[Peso] [decimal](5, 2) NULL,
	[Altura] [decimal](5, 2) NULL,
	[Temperatura] [decimal](5, 2) NULL,
	[IdMascota] [int] NULL,
 CONSTRAINT [PK_Registros.Salud] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Registros.Salud]  WITH CHECK ADD  CONSTRAINT [FK_Registros.Salud_Mascotas] FOREIGN KEY([IdMascota])
REFERENCES [dbo].[Mascotas] ([Id])
GO

ALTER TABLE [dbo].[Registros.Salud] CHECK CONSTRAINT [FK_Registros.Salud_Mascotas]
GO

