USE [master]
GO

/****** Object:  Database [ReseniasTechaDB]    Script Date: 7/1/2026 13:57:22 ******/
CREATE DATABASE [ReseniasTechaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ReseniasTechaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ReseniasTechaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ReseniasTechaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ReseniasTechaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ReseniasTechaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ReseniasTechaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ReseniasTechaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ReseniasTechaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ReseniasTechaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ReseniasTechaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ReseniasTechaDB] SET  MULTI_USER 
GO

ALTER DATABASE [ReseniasTechaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ReseniasTechaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ReseniasTechaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ReseniasTechaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ReseniasTechaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ReseniasTechaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ReseniasTechaDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [ReseniasTechaDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ReseniasTechaDB] SET  READ_WRITE 
GO



USE [ReseniasTechaDB]
GO

/****** Object:  Table [dbo].[Articulos]    Script Date: 7/1/2026 13:57:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Articulos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Descripcion] [nvarchar](100) NULL,
	[Categoria] [nvarchar](50) NULL,
	[Precio] [decimal](18, 0) NULL,
 CONSTRAINT [PK_Articulos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ReseniasTechaDB]
GO

USE [ReseniasTechaDB]
GO

/****** Object:  Table [dbo].[Usuarios]    Script Date: 7/1/2026 13:58:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Email] [nvarchar](100) NULL,
	[Pais] [nvarchar](50) NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [dbo].[Resenias]    Script Date: 7/1/2026 13:57:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Resenias](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdArticulo] [int] NULL,
	[IdUsuario] [int] NULL,
	[Puntuacion] [int] NULL,
	[Comentario] [nvarchar](100) NULL,
	[Fecha] [date] NULL,
 CONSTRAINT [PK_Resenias] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Resenias]  WITH CHECK ADD  CONSTRAINT [FK_Resenias_Articulos] FOREIGN KEY([IdArticulo])
REFERENCES [dbo].[Articulos] ([Id])
GO

ALTER TABLE [dbo].[Resenias] CHECK CONSTRAINT [FK_Resenias_Articulos]
GO

ALTER TABLE [dbo].[Resenias]  WITH CHECK ADD  CONSTRAINT [FK_Resenias_Usuarios] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuarios] ([Id])
GO

ALTER TABLE [dbo].[Resenias] CHECK CONSTRAINT [FK_Resenias_Usuarios]
GO


