USE [master]
GO

/****** Object:  Database [MascotasDB]    Script Date: 7/1/2026 14:34:55 ******/
CREATE DATABASE [MascotasDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MascotasDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MascotasDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MascotasDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MascotasDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MascotasDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MascotasDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MascotasDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MascotasDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MascotasDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MascotasDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MascotasDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MascotasDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MascotasDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MascotasDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MascotasDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MascotasDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MascotasDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MascotasDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MascotasDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MascotasDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MascotasDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MascotasDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MascotasDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MascotasDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MascotasDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MascotasDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MascotasDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MascotasDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MascotasDB] SET  MULTI_USER 
GO

ALTER DATABASE [MascotasDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MascotasDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MascotasDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MascotasDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MascotasDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MascotasDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MascotasDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [MascotasDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [MascotasDB] SET  READ_WRITE 
GO


USE [MascotasDB]
GO

/****** Object:  Table [dbo].[Mascotas]    Script Date: 7/1/2026 14:35:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Mascotas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Especie] [nvarchar](50) NULL,
	[Raza] [nvarchar](50) NULL,
	[FechaNacimiento] [datetime] NULL,
	[IdUsuario] [int] NULL,
 CONSTRAINT [PK_Mascotas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Mascotas]  WITH CHECK ADD  CONSTRAINT [FK_Mascotas_Usuarios] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuarios] ([Id])
GO

ALTER TABLE [dbo].[Mascotas] CHECK CONSTRAINT [FK_Mascotas_Usuarios]
GO



USE [MascotasDB]
GO

/****** Object:  Table [dbo].[Usuarios]    Script Date: 7/1/2026 14:35:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Apellido] [nvarchar](50) NULL,
	[Email] [nvarchar](100) NULL,
	[Clave] [nvarchar](50) NULL,
	[FechaRegistro] [date] NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



USE [MascotasDB]
GO

/****** Object:  Table [dbo].[RegistrosSalud]    Script Date: 7/1/2026 14:35:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RegistrosSalud](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FechaRegistro] [date] NULL,
	[Peso] [decimal](18, 0) NULL,
	[Altura] [decimal](18, 0) NULL,
	[Temperatura] [decimal](18, 0) NULL,
	[IdMascota] [int] NULL,
 CONSTRAINT [PK_RegistrosSalud] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RegistrosSalud]  WITH CHECK ADD  CONSTRAINT [FK_RegistrosSalud_Mascotas] FOREIGN KEY([IdMascota])
REFERENCES [dbo].[Mascotas] ([Id])
GO

ALTER TABLE [dbo].[RegistrosSalud] CHECK CONSTRAINT [FK_RegistrosSalud_Mascotas]
GO



USE [MascotasDB]
GO

/****** Object:  Table [dbo].[CitasVeterinarias]    Script Date: 7/1/2026 14:35:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CitasVeterinarias](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FechaCita] [date] NULL,
	[Razon] [nvarchar](100) NULL,
	[IdMascotas] [int] NULL,
 CONSTRAINT [PK_CitasVeterinarias] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CitasVeterinarias]  WITH CHECK ADD  CONSTRAINT [FK_CitasVeterinarias_Mascotas] FOREIGN KEY([IdMascotas])
REFERENCES [dbo].[Mascotas] ([Id])
GO

ALTER TABLE [dbo].[CitasVeterinarias] CHECK CONSTRAINT [FK_CitasVeterinarias_Mascotas]
GO



