USE [master]
GO

/****** Object:  Database [GaleriaDeArteDB]    Script Date: 7/1/2026 14:24:16 ******/
CREATE DATABASE [GaleriaDeArteDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GaleriaDeArteDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GaleriaDeArteDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GaleriaDeArteDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GaleriaDeArteDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GaleriaDeArteDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GaleriaDeArteDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GaleriaDeArteDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GaleriaDeArteDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GaleriaDeArteDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GaleriaDeArteDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GaleriaDeArteDB] SET  MULTI_USER 
GO

ALTER DATABASE [GaleriaDeArteDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GaleriaDeArteDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GaleriaDeArteDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GaleriaDeArteDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GaleriaDeArteDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [GaleriaDeArteDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [GaleriaDeArteDB] SET  READ_WRITE 
GO



USE [GaleriaDeArteDB]
GO

/****** Object:  Table [dbo].[Artistas]    Script Date: 7/1/2026 14:24:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Artistas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Pais] [nvarchar](50) NULL,
 CONSTRAINT [PK_Artistas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [GaleriaDeArteDB]
GO

/****** Object:  Table [dbo].[Exposiciones]    Script Date: 7/1/2026 14:24:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Exposiciones](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[FechaInicio] [date] NULL,
	[FechaFin] [date] NULL,
 CONSTRAINT [PK_Exposiciones] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



USE [GaleriaDeArteDB]
GO

/****** Object:  Table [dbo].[Obras]    Script Date: 7/1/2026 14:24:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Obras](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Titulo] [nvarchar](50) NULL,
	[Estilo] [nvarchar](50) NULL,
	[IdArtista] [int] NULL,
 CONSTRAINT [PK_Obras] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Obras]  WITH CHECK ADD  CONSTRAINT [FK_Obras_Artistas] FOREIGN KEY([IdArtista])
REFERENCES [dbo].[Artistas] ([Id])
GO

ALTER TABLE [dbo].[Obras] CHECK CONSTRAINT [FK_Obras_Artistas]
GO



USE [GaleriaDeArteDB]
GO

/****** Object:  Table [dbo].[ObrasExposiciones]    Script Date: 7/1/2026 14:25:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ObrasExposiciones](
	[IdObra] [int] NOT NULL,
	[IdExposicion] [int] NOT NULL,
 CONSTRAINT [PK_ObrasExposiciones] PRIMARY KEY CLUSTERED 
(
	[IdObra] ASC,
	[IdExposicion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ObrasExposiciones]  WITH CHECK ADD  CONSTRAINT [FK_ObrasExposiciones_Exposiciones] FOREIGN KEY([IdExposicion])
REFERENCES [dbo].[Exposiciones] ([Id])
GO

ALTER TABLE [dbo].[ObrasExposiciones] CHECK CONSTRAINT [FK_ObrasExposiciones_Exposiciones]
GO

ALTER TABLE [dbo].[ObrasExposiciones]  WITH CHECK ADD  CONSTRAINT [FK_ObrasExposiciones_Obras] FOREIGN KEY([IdObra])
REFERENCES [dbo].[Obras] ([Id])
GO

ALTER TABLE [dbo].[ObrasExposiciones] CHECK CONSTRAINT [FK_ObrasExposiciones_Obras]
GO

